config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :services do
    resources :bookings, only: :create
  end
  resources :bookings, except: :create
  get "/dashboard", to: "dashboards#index"

  resources :users, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :service
  belongs_to :user

  validates :status, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  validates :skill_name, presence: true
  validates :price_per_hour, presence: true
  validates :availability, presence: true

  include PgSearch::Model
  pg_search_scope :search_for_skills,
    against: [ :skill_name ],
    using: {
    tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :services
  has_many :bookings
  # has_many :bookings_as_student, through: :services, source: :bookings
  has_many :bookings_as_teacher, through: :services, source: :bookings

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :role])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.service = Service.find(params[:service_id])
    @booking.status = "pending"
    @booking.save
    redirect_to service_path(@booking.service), alert: 'Congratulations! You booked a Skill'
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to dashboard_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to booking_path
  end

  def new
    @booking = Booking.new()
  end

  def index
    @bookings = Booking.all
  end

  private

  def booking_params
    params.require(:booking).permit(:status, :service_id, :start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    if current_user.role == "teacher"
      @bookings = current_user.bookings_as_teacher
      @services = Service.where(user: current_user)
    end
    @student_booking = Booking.where(user: current_user)

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    services = Service.all
    sorted = services.sort {|s| s.bookings.size}
    @services = sorted.first(3)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:query].present?
      @services = Service.search_for_skills(params[:query])
    else
      @services = Service.all
    end
  end

  def new
    @service = Service.new
  end

  def show
    @service = Service.find(params[:id])
    @previous_booking = Booking.where(user: current_user, service: @service)
    @booking = Booking.new
    @teacher = User.find(@service.user_id)
  end

  def create
    @service = Service.new(service_params)
    @service.user = current_user
    if @service.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def search
    if params [:search].blank?
      redirect_to services_path
    else
      @input_searchbar = params [:search].downcase
      @results = Services.all.where("LIKE :search, search:", "%{@input_searchbar}%")
    end
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to dashboard_path
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.update(service_params)

    # no need for app/views/restaurants/update.html.erb
    redirect_to dashboard_path(@restaurant)
  end

  private

  def service_params
    params.require(:service).permit(:skill_name, :price_per_hour, :availability, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>This is the index page</h1>

app/views/bookings/new.html.erb
<h1> Create a new booking </h1>

app/views/dashboards/index.html.erb
<div class="container">
  <% if current_user.role == "teacher"  %>
  <h1> My services</h1>
  <div>
  <ul class="list-group list-group">
    <% @services.each do |service| %>
      <div class="bookings">
      <li class="list-group-item"><%= image_tag ("S_logo.jpg"), class: "img_small"%> <br>
      <strong>Lesson: </strong><%="#{service.skill_name} - ($#{service.price_per_hour} per hour)"  %>
      <%= link_to service_path(service), method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
      <%= link_to edit_service_path(service) do %>
      <i class="fas fa-edit"></i>
      <% end %>
      </li>
      </div>
    <% end %>
  </div>

  <br>
  <br>
  <br>
  <br>

  <h1> My booked services</h1>
  <div>
  <ul class="list-group list-group">
    <% @bookings.each do |b| %>
      <div class="bookings">
      <li class="list-group-item"><%= image_tag ("S_logo.jpg"), class: "img_small"%><br>
        <strong>Lesson: </strong><%= b.service.skill_name %>
          <%= simple_form_for b do |f| %>
          <%= f.input :status, label: 'Status:', collection:['pending','confirmed', 'cancelled'] %>
            <%= f.button :submit, "Submit", class: "btn btn-dark"%>
            <% end %>
      </div>
    <% end %>
  </div>
  <% end %>
  <br>
  <br>
  <br>
  <br>


  <h1> My bookings </h1>
  <div>
    <ul class="list-group list-group">
    <% @student_booking.each do |b| %>
      <div class="bookings">
        <li class="list-group-item"><%= image_tag ("S_logo.jpg"), class: "img_small"%><br> <strong>Lesson:</strong> <%= b.service.skill_name %><br> <strong>Status:</strong> <%= b.status %></li>
        <br>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Skillbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <div>
    <%# <p class="notice"><%= notice</p> %>
    <% unless alert.nil? %>
      <p class="alert alert-dark"><%= alert %></p>
    <% end %>
   </div>

   <div class= "page-container">
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <% if params[:controller] == "pages" %>
        <%= render "shared/banner" %>
      <% end %>
      <div class="content-container">
        <%= yield %>
      </div>
      <div class="footer-container"><%= render "shared/footer" %></div>
   </div>
  </body>

</html>

app/views/pages/home.html.erb
<%= render 'shared/features_overview' %>

app/views/services/edit.html.erb
<div class="container">
  <h1> Edit the service </h1>
  <%= simple_form_for @service do |f| %>
    <%= f.input :skill_name , placeholder: "What is your skill" %>
    <%= f.input :price_per_hour,placeholder: "How much per hour?" %>
    <%= f.input :availability, placeholder: "yes or no" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Update", class: "btn btn-dark" %>
  <% end %>
</div>

app/views/services/index.html.erb
<div class="container py-5">

  <h1> Services </h1>

  <div class="searchbar my-4" >

      <%= form_tag services_path, method: :get do %>
      <div class="form">
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Find a skill",
              autocomplete: 'off' %>
          <%= submit_tag "Search", class: "btn btn-dark" %>
          </div>
      <% end %>

  </div>
  <div class='cards'>
    <% @services.each do |s| %>
      <% if s.photo.attached? %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path s.photo.key, height: 300, crop: :fill %>')">
      <% else %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://wallpaperaccess.com/full/1078877.jpg)">
      <% end  %>
        <%= link_to s.skill_name, service_path(s), class:'link' %>
      </div>
    <% end %>
   </div>
</div>

app/views/services/new.html.erb
<div class="container">
  <h1> Create a new service </h1>
  <%= simple_form_for @service do |f| %>
    <%= f.input :skill_name , placeholder: "What is your skill?"%>
    <%= f.input :price_per_hour,placeholder: "How much per hour?"%>
    <%= f.input :availability, placeholder: "yes or no"%>
    <%= f.input :photo, as: :file%>
    <%= f.submit "Create", class: "btn btn-dark"%>
  <% end %>
</div>

app/views/services/show.html.erb
<%= render "shared/banner_service", service: @service %>
<div class="container">
  <div class="d-grid gap-4 mt-4">
    <%= render "shared/card_teacher",  teacher: @teacher %>
    <p><%=@service.user.bio %> </p>
    <div data-controller="form">
      <%= simple_form_for [@service, @booking] do |f| %>
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <% if @previous_booking.empty? %>
          <%= f.button :submit, "Book Skill", class: "btn btn-dark" %>
        <% else %>
          <%= f.button :submit, "Booked!", class: "btn btn-dark", disabled: true %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://wallpaperaccess.com/full/1078877.jpg);">
  <div class="container">
    <h1>Skillsbnb</h1>
    <p>Learn a skill! Change your life!</p>
  </div>
</div>

app/views/shared/_banner_service.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path service.photo.key, height: 300, crop: :fill %>')">
  <div class="container">
    <h1><%= service.skill_name %></h1>
    <p><%= @service.description %></p>
    <h3 style="color: white"><%= "($#{service.price_per_hour})" %></h3>
  </div>
</div>

app/views/shared/_button.html.erb
<a class="btn btn-flat" href="#">Book now</a>

app/views/shared/_card.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
  Service
</div>

app/views/shared/_card_teacher.html.erb
<div class="card-teacher">
<img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
  <h4><%= "#{teacher.first_name} #{teacher.last_name}" %></h4>
  <h5><i class="fas fa-star "></i><%= rand(1.0..5.0).round(1) %></h2>
</div>

app/views/shared/_features_overview.html.erb
<div class="container">
`	<section class="features-overview" id="features-section" style="text-align:  center;">
    <div class="content-header">
      <h2>Hot right now 🔥</h2>
      <h6 class="section-subtitle text-muted">Have a look at our top 3 skills at the moment!</h6>
    </div>
    <div class="d-flex justify-content-between">
      <% @services.each do |s| %>
        <div class="d-md-flex justify-content-between">
          <div class="grid-margin d-flex justify-content-start">
            <div class="features-width">
              <div class="">
                <%= cl_image_tag s.photo.key , class: "home-img"%>
              <%# <img src="images/Group12.svg" alt="" class="img-icons"> %>
                <h5 class="py-3"><%= s.skill_name %></h5>
                <div class="home-service-description"><p class="text-muted"><%= s.description %></p></div>
                <%= link_to "See More", s, class: "btn btn-dark" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i>  SkillBnb
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
      <%= link_to root_path, class:"navbar-brand" do %>
        <%= image_tag ("skillsbnb_logo.jpg") %>
      <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <% if current_user && current_user.role == "teacher" %>
              <a class="nav-link" href="/services/new">Create Service</a>
            <%end%>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/services">Available Services</a>
          </li>
          <% if current_user %>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://images.unsplash.com/photo-1548449112-96a38a643324?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=80&q=80" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user %>
                <a class="dropdown-item" href="/dashboard">Dashboard</a>
              <%end%>

              <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
          <%else %>
            <li class="nav-item">
              <a class="nav-link" href="/users/sign_up">Sign up</a>
            </li>
          <% end %>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>